baseURL = "http://jandolezal.cz/"
title = "jandolezal.cz"
languageCode = "cs-cz"
newContentEditor = "vi"
theme = "mediumish-gohugo-theme"
pygmentsStyle = "native"
uglyurls = true
copyright = "Jan Doležal - All rights reserved"
disqusShortname = "jandolezal"

[author]
  name = "Jan Doležal"

[permalinks]
  blog = ":year-:month-:day-:title"
  tags = "tags-:title"

[params.social]
  github = "dolezaljan"
  #linkedin = ""
  #xing = ""
  #medium = ""
  twitter = "cagedHamster"
  instagram = "_jandolezal"

## Main Menu
[[menu.main]]
    name = "Intro"
    weight =   1
    identifier = "intro"
    url = "/"

[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog.html"

[[menu.main]]
    name = "RSS"
    weight = 101
    identifier = "rss"
    url = "/files/blog/index.xml"
