baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "mediumish-gohugo-theme"
uglyurls = true
disqusShortname = "jandolezal"

[permalinks]
  blog = ":year-:month-:day-:title"
  tags = "tags-:title"

## Main Menu
[[menu.main]]
    name = "Intro"
    weight =   1
    identifier = "intro"
    url = "/"

[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog.html"

[[menu.main]]
    name = "RSS"
    weight = 101
    identifier = "rss"
    url = "/files/index.xml"
